create table if not exists public.books (
  id bigint generated by default as identity primary key,
  title text not null,
  author text not null,
  genre text not null default 'Other',
  status text not null default 'unread'
    check (status in ('unread', 'reading', 'read')),
  created_at timestamptz not null default now()
);

alter table public.books enable row level security;

create policy "Anyone can read books"
  on public.books for select
  using (true);

create policy "Anyone can add books"
  on public.books for insert
  with check (true);
